kitchen counter Interaction
zero-to-mastery/ZTM-Quest pull request #188
Opened 2024-10-28 17:54 UTC by Tanisha800

if you like the interaction please add it to hacktoberfest2024

2024-10-29 07:36 UTC, r4pt0s requested changes
Hi @Tanisha800,
Your PR looks like a duplicate of #186
Even the comment in the pull request.

Can you change the behavior of your implementation here a bit?

2024-10-29 10:16 UTC, Tanisha800 reviewed
commited the changes

2024-10-29 10:16 UTC, Tanisha800 commented on src/interactions/map_campus_house_1/kitchen_counter.interaction.js
> -    player.onCollide('kitchen_slab', async () => {
kitchen_slab must be change to kitchen_counter

2024-10-29 16:33 UTC, r4pt0s commented
@Tanisha800 there is still a merge conflict. Can you please fix it 🙏🏻?

2024-11-02 06:37 UTC, r4pt0s commented
Closed due to inactivity

2024-11-02 06:37 UTC, closed without merging