added chest object
zero-to-mastery/ZTM-Quest pull request #192
Opened 2024-10-29 21:17 UTC by codewithsupra

Added a chest object that gets more points

2024-10-30 05:54 UTC, r4pt0s requested changes
@codewithsupra there are a few changes to make in your PR.
Also, make sure you check the game with your changes locally with
```bash
npm run dev
```
To make sure there are no errors.

2024-10-30 05:54 UTC, r4pt0s commented on public/assets/sprites/chest.png
This is not really a sprite. If looks more like a normal image which doesn't fit into the style which the entire game follows. Can you replace it with a 2D top-down pixel chest sprite?

2024-10-30 05:54 UTC, r4pt0s commented on src/gameObjects/map_start/chest.gameObject.js
> +      k.pos(map.pos.x + spawnpoints.chest.x, map.pos.y + spawnpoints.chest.y),
Unfortunately, there is no spawnpoint.chest available for now.
Have a look at other game object files to get an idea how you can place objects differently in such a case

2024-10-30 05:54 UTC, r4pt0s commented on yarn.lock
Please remove the yarn.lock file because we use npm primarily for the project.

2024-10-30 08:32 UTC, closed without merging

2024-10-31 12:24 UTC, codewithsupra commented on yarn.lock
i have added as a new branch. please check