Adding game's store logic in JS
zero-to-mastery/ZTM-Quest pull request #44
Opened 2024-10-01 18:03 UTC by lorenzomiro

I was thinking that this game would need some logic for a store that would be used to buy and sell items. This is a sample interaction that I made to get that started.

2024-10-01 19:13 UTC, r4pt0s requested changes
@lorenzomiro could you maybe add the interaction to map_city instead of map_start?
In map_city, we already have set up two potential buildings with enter map tags where one of them could be a store.
Hava a look at [additional map infos](https://github.com/zero-to-mastery/ZTM-Quest/blob/main/additional-map-info%2Fmap_city%2Fobjects_map_city_1.png) where you can see the tag name of the buildings which you can use in your onCollide method.

2024-10-01 20:38 UTC, lorenzomiro commented
Pull request updated with "Updated with map_city interactions moved out from map_start"

2024-10-02 06:52 UTC, r4pt0s commented on src/interactions/map_arcade/index.js
please move you additions to [map_city interactions](https://github.com/zero-to-mastery/ZTM-Quest/blob/main/src/interactions/map_city/index.js)

2024-10-02 06:54 UTC, r4pt0s commented on src/interactions/map_city/enterMapArcade.interactions.js
Revert the changes of this file and move your logic into a new file with the name `enterMapStore.interactions.js`

2024-10-02 06:57 UTC, r4pt0s commented on src/interactions/map_city/enterStoreMainArea.interaction.js
> +import { sampleStoreInteraction, sampleArcadeInteraction } from './enterMapArcade.interactions';
move your code from enterMapArcade.interactions to this file because of my comment to revert the enterMapArcade.interactions.js file

2024-10-02 06:57 UTC, r4pt0s commented on src/interactions/map_city/enterStoreMainArea.interaction.js
> +    //if user runs into the house, show them the house
pleaseo remove this code because there is already a enter_map_arcade interaction. otherwise it is not possible anymore to go into the arcade

2024-10-02 06:59 UTC, r4pt0s commented on src/interactions/map_city/enterStoreMainArea.interaction.js
> +        });*/
ther is already the building here. You made it already right. Just add the sampleTinyHouseInteraction function and we are good to go

2024-10-02 06:59 UTC, r4pt0s commented on src/interactions/map_start/enterStoreMainArea.interaction.js
please remove this file because we have it in `interactions/map_city` in your PR

2024-10-02 07:00 UTC, r4pt0s requested changes
See comments.
Also make sure to update your PR with the latest changes of the main branch

2024-10-09 19:16 UTC, r4pt0s commented
@lorenzomiro closed due to inactivity. Feel free to reopen the Pr or to create a new one. There were a lot of changes happening.

2024-10-09 19:16 UTC, closed without merging