Jessie arcade
zero-to-mastery/ZTM-Quest pull request #85
Opened 2024-10-04 12:37 UTC by MIhnatco

Adding 'Jessie' to map arcade

2024-10-04 13:40 UTC, r4pt0s requested changes
@MIhnatco please check the failed checks output.
As far I saw, you have used a method which doesn't exist anymore because it got replaced with another one

2024-10-04 14:26 UTC, r4pt0s commented
@MIhnatco and could you maybe add at least a different conversation text?
Otherwise Jesse would just be a copy of Mister Fu :sweat_smile:

2024-10-06 18:02 UTC, r4pt0s requested changes

2024-10-06 18:02 UTC, r4pt0s commented on src/interactions/map_start/misterFu.interaction.js
Please revert the changes to how this file looks now
https://github.com/zero-to-mastery/ZTM-Quest/blob/main/src/interactions/map_start/misterFu.interaction.js

2024-10-07 21:37 UTC, b-hexsoul requested changes

2024-10-07 21:37 UTC, b-hexsoul commented on src/interactions/map_arcade/jessie.interaction.js
> +        npcInteractionHandler(player, jessie.name, k, () => {
```npcInteractionHandler``` is being used incorrectly in this exported function. Please look at bruno.interaction.js

2024-10-08 06:08 UTC, r4pt0s requested changes
@MIhnatco could you plase make the requested changes?
Thank you!

2024-10-08 06:08 UTC, r4pt0s commented on src/gameObjects/map_arcade/jessie.gameObject.js
> +    k.loadSprite('jessie', './characters.png', {
the path to the assets has changed it is ow `./assets/sprites/characters.png`
Can you fix this please :pray: ?

2024-10-09 14:57 UTC, r4pt0s approved these changes

2024-10-09 14:58 UTC, merged